### ISSUE TITLE
Unable to switch framgent using the bottom bar

### ISSUE THREAD

**Issue by Penguin5681** [st235/ExpandableBottomBar#102]
`package com.example.bloom;

import android.graphics.Color;
import android.os.Bundle;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.fragment.app.Fragment;

import github.com.st235.lib_expandablebottombar.ExpandableBottomBar;
import github.com.st235.lib_expandablebottombar.Menu;
import github.com.st235.lib_expandablebottombar.MenuItemDescriptor;

public class DashboardActivity extends AppCompatActivity {
    ExpandableBottomBar bottomNavigationBar;
    public final int CONSTRAINT_LAYOUT = R.id.frame_layout;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_dashboard);
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        bottomNavigationBar = findViewById(R.id.bottom_navigation_bar_dashboard_activity);
        Menu bottomMenu = bottomNavigationBar.getMenu();

        bottomMenu.add(new MenuItemDescriptor.Builder(
                getApplicationContext(),
                R.id.home_icon_menu_item,
                R.drawable.home_icon_empty,
                R.string.home,
                Color.GRAY
        ).build());

        bottomMenu.add(new MenuItemDescriptor.Builder(
                getApplicationContext(),
                R.id.app_limits_icon_menu_item,
                R.drawable.app_limits_icon_empty,
                R.string.app_limits,
                Color.GRAY
        ).build());

        bottomMenu.add(new MenuItemDescriptor.Builder(
                getApplicationContext(),
                R.id.app_usage_icon_menu_item,
                R.drawable.app_usage_icon_hourglass_bottom,
                R.string.time_spent,
                Color.GRAY
        ).build());

        bottomMenu.add(new MenuItemDescriptor.Builder(
                getApplicationContext(),
                R.id.profile_icon_menu_item,
                R.drawable.profile_icon_empty,
                R.string.profile,
                Color.GRAY
        ).build());

        bottomNavigationBar.setOnItemSelectedListener((view, menuItem, aBoolean) -> {
            int itemId = menuItem.getId();
            if (itemId == R.id.home_icon_menu_item)
                getSupportFragmentManager().beginTransaction().replace(CONSTRAINT_LAYOUT, new HomeFragment()).commit();
            else if (itemId == R.id.app_usage_icon_menu_item)
                getSupportFragmentManager().beginTransaction().replace(CONSTRAINT_LAYOUT, new AppUsagesFragment()).commit();
            else if (itemId == R.id.app_limits_icon_menu_item)
                getSupportFragmentManager().beginTransaction().replace(CONSTRAINT_LAYOUT, new AppLimitsFragment()).commit();
            else if (itemId == R.id.profile_icon_menu_item)
                getSupportFragmentManager().beginTransaction().replace(CONSTRAINT_LAYOUT, new ProfileFragment()).commit();
            return null;
        });
    }
}`

**Comment by st235** [comment]
Hello @Penguin5681,

Thank you for providing the feedback. Let's figure out what's happening.

Can you, please, show your layout file?
I am wondering if this layout corresponds to the right one

```
public final int CONSTRAINT_LAYOUT = R.id.frame_layout;
```


Moreover, it would be nice if you can attach your android studio project.

Looking forward to hearing from you.
