### ISSUE TITLE
Increase Font Size

### ISSUE THREAD

**Issue by pythongiant** [st235/ExpandableBottomBar#16]
How Can You Increase font size?

**Comment by st235** [comment]
Hi, for now its locked and has fixed size of `15 sp`
As far as I know, `BottomNavigationView` does not support officially font size change.
In my opinion, its really not necessary.

But if u still want to do that, there is an item builder which takes [`CharSequence`](https://github.com/st235/ExpandableBottomBar/blob/master/lib_expandablebottombar/src/main/java/github/com/st235/lib_expandablebottombar/ExpandableBottomBarMenuItem.kt#L37), so u permitted to use `SpannableString` here.

For example, it may looks like:
```
        val customSizeText = SpannableString(... some text ...);
        customSizeText.setSpan(AbsoluteSizeSpan(18.toPx(), true), start, end, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
        bottomBar.addItems(
                ExpandableBottomBarMenuItem.Builder(this)
                        .addItem(R.id.icon_likes, R.drawable.ic_likes).text(customSizeText).colorRes(R.color.colorLike).create()
                        .build()
        )
```

**Comment by st235** [comment]
@pythongiant, is this problem still actual?

**Comment by alaa-abuzarifa** [comment]
> ```
>  val customSizeText = SpannableString(... some text ...);
>         customSizeText.setSpan(AbsoluteSizeSpan(18.toPx(), true), start, end, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
>         bottomBar.addItems(
>                 ExpandableBottomBarMenuItem.Builder(this)
>                         .addItem(R.id.icon_likes, R.drawable.ic_likes).text(customSizeText).colorRes(R.color.colorLike).create()
>                         .build()
>         )
> ```

How can I add multiple items using this approach? It gives me an error when I add multiple `.addItem(...)` ??

**Comment by st235** [comment]
@alaa-abuzarifa hi 👋,

what's the error appears?

**Comment by st235** [comment]
The code should be like:

```
        val text = SpannableString("Hello world")
        text.setSpan(AbsoluteSizeSpan(32), 0, text.length, SpannableString.SPAN_EXCLUSIVE_EXCLUSIVE)

        bottomBar.addItems(
                ExpandableBottomBarMenuItem.Builder(this)
                        // item with custom text size
                        .addItem(R.id.icon_settings, R.drawable.ic_settings).text(text).color(Color.parseColor("#be9c91")).create()
                        .build()
        )
```
