### ISSUE TITLE
Can you make this library of JAVA language？

### ISSUE THREAD

**Issue by ZxyTx** [st235/ExpandableBottomBar#17]
This library is really beautiful. I like it very much. Can you make a Java language of this library?

**Comment by st235** [comment]
Hi! Thanks for your interest in this library.
What do u mean `Java language of this library`?
Java is already supported, you can find Java usage example [here](https://github.com/st235/ExpandableBottomBar/blob/master/app/src/main/java/github/com/st235/expandablebottombar/JavaActivity.java).

**Comment by ZxyTx** [comment]
@st235 Okay, I found it. Thank you.

**Comment by st235** [comment]
@ZxyTx, no problem!
