### ISSUE TITLE
How am I supposed to integrate this project?

### ISSUE THREAD

**Issue by zunjae** [st235/ExpandableBottomBar#2]
Where can I download it from? Where is it hosted?

The readme only contains an identifier and version number (`implementation 'com.github.st235:expandablebottombar:0.4'`) but where is this downloaded from?

Could you add some instructions?

**Comment by zunjae** [comment]
Nevermind, I'm using https://github.com/gauravk95/bubble-navigation now. This project is hosted on JCenter

**Comment by st235** [comment]
I am so sorry for late delay,
it's published in jcenter too. There were some problems with jcenter integrations, but now it's fixed and lib will be available from jcenter by the end of the day!
Hopefully, it will help you.
