### ISSUE TITLE
Runtime updation of MenuItem Values ?

### ISSUE THREAD

**Issue by sachinrmcom** [st235/ExpandableBottomBar#25]
Runtime updation of MenuItem Values ?

or invalidation of bottomBar

**Comment by st235** [comment]
Hi ✋ 
You always able to call setItems with new list of values.
Unfortunately, it has not been planned yet to support such a functionality.

Can you provide detailed description why you need this feature, please?

**Comment by myJarvis** [comment]
hi , ok got it , but i added few functionalities , will make a PR soon :)

**Comment by st235** [comment]
ok, will wait!
thanks
