### ISSUE TITLE
How to use onItem click listener in java

### ISSUE THREAD

**Issue by rajam1215** [st235/ExpandableBottomBar#28]
Hello @st235 

Please describe some code peace, how to use setOnItemSelected listener in java class, and describe add multiple fragments. it is very useful library

Thanks

**Comment by st235** [comment]
Hi @rajam1215, first of all thanks for reaching me out!
I am really sorry I cannot answer your earlier 😢 

Yeah, you're absolutely right, there are no examples how to use callbacks in Java, but I've already fixed it. 

To properly handle callbacks in Java you should create anonymous instance of `Function2<View, ExpandableBottomBarMenuItem, Unit>` class and override `invoke` method. As Java do know nothing about Kotlin `Unit` type, you should return `null` or `Unit.INSTANCE` as a result of invoke, sorry, for such an inconvenient syntax. 

Example will look like:


```java
        bottomBar.setOnItemSelectedListener(new Function2<View, ExpandableBottomBarMenuItem, Unit>() {
            @Override
            public Unit invoke(View view, ExpandableBottomBarMenuItem expandableBottomBarMenuItem) {
                // code goes here
                return Unit.INSTANCE;
            }
        });
``` 

If you're using Java 8 syntax, then lambda expression will be enough here

```java
        bottomBar.setOnItemSelectedListener((view, item) -> {
            Log.d(TAG, "selected: " + item.toString());
            return null;
        });
```

For more details u're able to find updated examples [here](https://github.com/st235/ExpandableBottomBar/blob/master/app/src/main/java/github/com/st235/expandablebottombar/JavaActivity.java#L33).

**Comment by rajam1215** [comment]
Hello @st235
Thanks for the solution.
