### ISSUE TITLE
How can I remove menuitems title?

### ISSUE THREAD

**Issue by Jaden2208** [st235/ExpandableBottomBar#31]
First of all thank you for make this library :)

Is this the only way to remove menuitems title?
``` xml
<item
   android:id="@+id/home"
   android:title=""
   ... />
```
It has some padding on title space when I select it. but I don't want it.
are there any other way to remove it?

**Comment by st235** [comment]
@Jaden2208 Hi 👋 

I really appreciate you've chosen my library over a bunch of libraries at Github 😺  Yeah, unfortunatelly, its the only way to remove title for now, but the good news is I am on it and will add this feature in a close future. 

Moreover, I am always welcome for new contributors, so, do not hesitate to create pull requests, if you already have something or in future.

Stay tuned!

**Comment by st235** [comment]
Hi @Jaden2208 👋

I've investigated the ability to provide requested feature and faced with animation issues. Icons without text looks really ugly and there are nothing to animate inside of it.

Could you, please, share your experience, how are you going to use this feature? Do you use bottom bar without any text, or you're following the mixed style: some items does have text title, but some of then doesnt? Which one animation do you expect to see in a case if there is no text? 

I would be really happy if you will provide some screens of usage examples.

Thanks in advance for your replay

**Comment by st235** [comment]
@Jaden2208 Hi once again

Do I have a chance you take a look at this thread? If it's possible to provide additional info, I would be very happy
