### ISSUE TITLE
Cannot resolve method addItems(?)

### ISSUE THREAD

**Issue by yasandev** [st235/ExpandableBottomBar#4]
I just started a fresh project and wanted to add this library to my app, but i cant add items to the bottom bar and the method doesnt work. It is a java project but as far as I know it shouldnt matter.

![d](https://user-images.githubusercontent.com/41836211/56409810-ea2a5900-628f-11e9-8b29-937ee98b806b.PNG)

How can I fix this? I dont think I did anything wrong since there is not much that I can do wrong for this library.

**Comment by st235** [comment]
Hi, thanks for using library, I will investigate your problem in a few hours.

**Comment by st235** [comment]
there was the problem with proguard rule. so, I have fixed it and you`ll need to update your library to 0.6 ;D
thanks for reporting.

**Comment by yasandev** [comment]
Thanks for fixing it. I will try again!
