### ISSUE TITLE
MVVM Support (Navigation component)

### ISSUE THREAD

**Issue by rajam1215** [st235/ExpandableBottomBar#40]
Hello @st235 

Please add MVVM support

navController = Navigation.findNavController(this, R.id.nav_host_fragment);

So user can use this library with navigation component also. so user can  handle only one activity and all fragment.

Thanks

**Comment by st235** [comment]
@rajam1215 Hi 👋 

Firstly I would like to say thank you for using this library. Yeah, I will take a look at what I can do here.

Stay tuned

**Comment by st235** [comment]
@rajam1215 Hello 👋 

Thanks for your feature proposal. Looks like this feature may be really useful for community. 
Unfortunately, I cannot deliver the support of Navigation Components directly to `NavigationUI` class as it doesn't use interfaces but does use real implementations of `NavgationDrawer`, `Toolbar` or `BottomNavigationView`. Indeed it was not the best solution from developers side, but I found out a solution.

I created some kind of fork of NavigationUI class, which applied to `ExpandableBottomBar`. Currently, it would be possible to use `ExpandableBottomBarNavigationUI` with your navigation graph.

The usage is pretty simple

```kotlin
        /**
         * Call looks like NavigationUI.setupWithNavController(bottomNavigation, navigationController)
         * for native BottomNavigationView
         */
        ExpandableBottomBarNavigationUI.setupWithNavController(bottomNavigation, navigationController)
```

All sample is located in the sample app at `NavigationComponentActivity` class. To bring this class into live I will update the library to `1.1.7` during a couple of hours.

Thank you for such a nice proposal!

**Comment by st235** [comment]
`1.1.7` is live now

**Comment by rajam1215** [comment]
@st235 hello
ok i'll implement this in real project. then i'll come to you, it is work perfect or not.

**Comment by rajam1215** [comment]
@st235  Hello

I see in project it is working fine now, but i don't know, how its behavior with other functionality. 

and **one more feature it need may be**, for example, if user click on fragment view object like button, then next fragment open with navigation component, that time if user want to hide bottom navigation, then how they will achieve this thing, because bottom navigation is fix at bottom.

It is very unique thing if it is  implement in it.

**Comment by st235** [comment]
@rajam1215 Thanks for your feedback.

I very appreciate it. I suppose you're talking about hiding according to some "dive deep"-like navigations. You are always welcomed to open Pull Request here if you're thinking some behaviour is missing here, but I reckon its not a common case.

In your case, I would recommend listening destination changed events with `addOnDestinationChangedListener`, and hide/reveal views according to items order.

**Comment by rajam1215** [comment]
Hello @st235 

**ExpandableBottomBarNavigationUI** this class not come in 1.1.7 version. please check once.

Thanks

**Comment by st235** [comment]
Yeah, of course, will recheck asap.

**Comment by st235** [comment]
@rajam1215 thanks for the report!

There was a problem at `1.1.7` version, now its fixed! Latest changes included at `1.1.8`.

**Comment by rajam1215** [comment]
> @rajam1215 thanks for the report!
> 
> There was a problem at `1.1.7` version, now its fixed! Latest changes included at `1.1.8`.

Hello @st235 

Thanks for the correction. i am working with **addOnDestinationChangedListener** with navigation components and its work good, but need to change toolbar title as well with deep navigation fragments. any suggestions.

Thanks

**Comment by st235** [comment]
Hi @rajam1215,

Thanks for feedback. If you listen **addOnDestinationChangedListener** why you can’t change toolbar title from this callback?

**Comment by rajam1215** [comment]
NO @st235 

I am talking about if you go one fragment to other, and need to set title on toolbar with own fragment data. means you have to set **xyz** fragment data on toolbar it is entirely diff from **onDestinationChangeListener**

not to set title **onDestinationChangeListener**

**Comment by st235** [comment]
It's still not clear for me what problem you're trying to solve.
Anyway, how did you solve it with `NavigationUI`, maybe if you will provide some code examples for this case for `NavigationUI` perspective, I will figure out how to help you.

**Comment by rajam1215** [comment]
> Sorry, but it's still not clear for me what problem you're trying to solve.
> Anyway, how did you solve it with `NavigationUI`, maybe if you will provide some code examples for this case from `NavigationUI` perspective, I will figure out how to help you.

for example
@Override
    public void onDestinationChanged(@NonNull NavController controller,
                                     @NonNull NavDestination destination,
                                     @Nullable Bundle arguments) {
        int id = destination.getId();
        if (id == R.id.nav_products || id == R.id.nav_detail)
            bottomNavigation.setVisibility(View.GONE);
        else
            bottomNavigation.setVisibility(View.VISIBLE);
    }

i can change the toolbar title from here easily with **onDestinationChanged**

@Override
    public boolean onNavigationItemSelected(@NonNull MenuItem item) {
        int id = item.getItemId();
        switch (id) {
            case R.id.nav_category:
                navController.navigate(R.id.nav_category);

with navigation i select other page like category. both function i use in main activity.

But when i go Category fragment, means in other fragment.

then i click on view item of category fragment with this
Bundle bundle = new Bundle();
            bundle.putString("name", subCat.getSeo());

            NavController navController = Navigation.findNavController(activity, R.id.nav_host_fragment);
            navController.navigate(R.id.action_Cat_to_Product, bundle);

now i go to other fragment. that time how can i change the toolbar title, coz now i dont have addDestinationChangeListener callback.

Do you think can i use addDestinationChangeListener callback in every fragment with navController

**Comment by st235** [comment]
Hi @rajam1215 

Thanks for the provided code. If I understood u correctly, this problem is out of the of `ExpandableBottomBar` and completely rely on your architecture approach. 

As I suppose, there are a lot of possible different solutions. For example, if you always need to set title from the fragments, you may set title from each fragment separately, ie inside of your fragment `(activity as? AppCompatActivity).supportedActionBar?.title = "Fragment title"`. You offered another nice approach - its possible for you to listen to destination change inside of the fragment.

Hopefully, this will help you.

**Comment by rajam1215** [comment]
Hello @st235 

Thanks for the reply and suggestion, yes it is give me help,  please approach me if you are stuck in any issue i'll there.

Thanks

**Comment by st235** [comment]
@rajam1215 cool, thank you! 

PS: You're always welcomed here!
