### ISSUE TITLE
avoid recreation of fragment

### ISSUE THREAD

**Issue by rajam1215** [st235/ExpandableBottomBar#44]
hello @st235 

sins the MVVM support it is awesome, but we need one more enhancement in the library, so Fragment not create every time when any bottom menu item clicked with MVVM

Thanks

**Comment by st235** [comment]
Hi @rajam1215,

sorry for a bit late replay. Did you check the default BottomBarNavigation view? Does it behave in an expected way? Also, did I understand you correctly - double-clicking on the same item causes Fragment recreation? If you don't mind, it would be really cool, if you can record a small video, which reflects wrong behaviour.

Looking forward to hearing from you

**Comment by rajam1215** [comment]
> Hi @rajam1215,
> 
> sorry for a bit late replay. Did you check the default BottomBarNavigation view? Does it behave in an expected way? Also, did I understand you correctly - double-clicking on the same item causes Fragment recreation? If you don't mind, it would be really cool, if you can record a small video, which reflects wrong behaviour.
> 
> Looking forward to hearing from you

Hello @st235 

I ma very glade to see you again, i know the default behavior navigation bottom, but this is not use only for show activity or fragment, but in this library we move forward already, it have MVVM support, but default doesn't, we need to avoid the recreation of fragment, now please check what is happen right now. 

double-clicking on the same item causes Fragment recreation,
no it's not, it recreate again when click on other menu item, 
it will recreate again and again

i make one little video,it will clear your query
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16591300/87222181-5f031a80-c38f-11ea-85e0-e7e7eb9206e5.gif)

Please check once.

**Comment by rajam1215** [comment]
Hello @st235 

Please reply, it is bit late. i am waiting, Looking forward to hearing from you

Thanks

**Comment by st235** [comment]
Hi @rajam1215,
sorry, it was a really crazy week. I'll be able to take a look at the problem only at the end of this week.

PS: However, it's always welcomed any kind of contribution here. So, if you have any ideas on how to solve this problem, do not hesitate, please, to create a pull request.

Kind regards,
Alexander Dadukin

**Comment by rajam1215** [comment]
Hello @st235 

not an issue, please see on the issue end of the week, but i have one solution for that.

`public class MainActivity extends AppCompatActivity {

final Fragment fragment1 = new HomeFragment();
final Fragment fragment2 = new DashboardFragment();
final Fragment fragment3 = new NotificationsFragment();
final FragmentManager fm = getSupportFragmentManager();
Fragment active = fragment1;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
    setSupportActionBar(toolbar);


    BottomNavigationView navigation = (BottomNavigationView) findViewById(R.id.navigation);
    navigation.setOnNavigationItemSelectedListener(mOnNavigationItemSelectedListener);

    fm.beginTransaction().add(R.id.main_container, fragment3, "3").hide(fragment3).commit();
    fm.beginTransaction().add(R.id.main_container, fragment2, "2").hide(fragment2).commit();
    fm.beginTransaction().add(R.id.main_container,fragment1, "1").commit();

}


private BottomNavigationView.OnNavigationItemSelectedListener mOnNavigationItemSelectedListener
        = new BottomNavigationView.OnNavigationItemSelectedListener() {

    @Override
    public boolean onNavigationItemSelected(@NonNull MenuItem item) {
        switch (item.getItemId()) {
            case R.id.navigation_home:
                fm.beginTransaction().hide(active).show(fragment1).commit();
                active = fragment1;
                return true;

            case R.id.navigation_dashboard:
                fm.beginTransaction().hide(active).show(fragment2).commit();
                active = fragment2;
                return true;

            case R.id.navigation_notifications:
                fm.beginTransaction().hide(active).show(fragment3).commit();
                active = fragment3;
                return true;
        }
        return false;
    }
};`

**Comment by st235** [comment]
@rajam1215, hi 👋

Hopefully, you are well. I take a look at the problem. I tried to reproduce similar behaviour with default android components, so I've changed `ExpandableBottomBar` to

```kotlin
    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottomNavigation"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:backgroundTint="#fff"
        app:menu="@menu/navigation_menu"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent" />
```

and also used NavigationUI is an alternative for native android view.

```kotlin
 NavigationUI.setupWithNavController(bottomNavigation, navigationController)
```

Unfortunately, the behaviour you mentioned below is not followed by material design components. As it's not a native behaviour, I cannot implement it in this library. The users will not expect such behaviour at this component.

Also, I've made a small video of `BottomNavigationView`

![device-2020-07-19-223556](https://user-images.githubusercontent.com/14966197/87883605-44751500-ca11-11ea-8603-d9f8582f521c.gif)

PS: also, I looked at the provided sample. The main highlight here: they don't use `NavigationUI`, but do use a custom extension (`BottomNavigationView#setupWithNavController) to provide required behaviour. 

Kind regards,
Alexander Dadukin

**Comment by rajam1215** [comment]
@st235 hello

I understand what you want to say, it is not necessary to add on this library,  but in my suggestion this feature you can see in maximum apps, **_you can check from your side also, those who use bottom navigation in the app_**. **coz some time user don't want to recreate the fragment again and again**, **_user always want to use it from where he/she left_**, i hope you can understand, 

you can add this thing in your lib, **_if user want to use this functionality in app, they can use, if not they can not use_**

Thanks and Regards 
Bishal Malick

**Comment by st235** [comment]
Good morning, @rajam1215 👋

Thank you for provided information, I really appreciate it. However, as I wrote below - it's not a default behavior for alternative native android widget. Moreover, it looks like as an application layer responsibility to cache fragments. I can recommend you to look at fragmentFactory - probably, it will cover you case.

Best wishes,
Alex

**Comment by rajam1215** [comment]
@st235 same2u

very thanks from suggestion i will defiantly R&D on that (Fragment factory), but i can handle this with giving example of **_(MainActivity)_** in the previous comment, it is very good technique to handle this thing, but coder need to handle this code without progress dialog, **_coz progress dialog overlap the fragment screens_**.

means if you use progress dialog in second screen, it will show in your first screen, coz above technique create the all fragments in ONCE, 

may be it give help to some user, they read are comments. because we can also use this technique in  ExpandableBottomBar, i check it already, coder need to use 

        bottomBar.setOnItemSelectedListener(new Function2<View, ExpandableBottomBarMenuItem, Unit>() {
            @Override
            public Unit invoke(View view, ExpandableBottomBarMenuItem expandableBottomBarMenuItem) {
                // code goes here
                return Unit.INSTANCE;
            }
        });

If you're using Java 8 syntax, then lambda expression will be enough here

        bottomBar.setOnItemSelectedListener((view, item) -> {
            Log.d(TAG, "selected: " + item.toString());
            return null;
        });

Thanks and regards
Bishal Malick
