### ISSUE TITLE
bottom bar has a peek height

### ISSUE THREAD

**Issue by jedi2610** [st235/ExpandableBottomBar#51]
![screencapture_00002](https://user-images.githubusercontent.com/30691152/91021299-38cccd80-e611-11ea-8484-422d6cbba6e3.gif)

**Comment by st235** [comment]
Will be fixed at `1.2.3`

**Comment by st235** [comment]
`1.2.3` is live now

**Comment by st235** [comment]
@jedi2610 Can you please confirm that problem really solved?

**Comment by jedi2610** [comment]
alr cool thanks. okay i'll check if it really works

**Comment by st235** [comment]
Yeah, cool!

This commit contains all the changes: https://github.com/st235/ExpandableBottomBar/commit/427b87cbb158a9aeffa349d6d82edd8c0fb7ff5f

But the main problem was `getMaxScrollDistance` method. It didn't take into account the margin of the view

**Comment by jedi2610** [comment]
hey me again, this is not exactly an issue nut i need some help. i actually have three fragments setup with the bottom bar and the bottom bar itself in my main activity which has a coordinator layout. and the home fragment has a recycler view. but when i scroll the recycler view the bottom bar is not scrolling along with it. the `layout_behaviour` for the bottom bar is set to `github.com.st235.lib_expandablebottombar.behavior.ExpandableBottomBarScrollableBehavior` but even then it is not working. can you help me with it?

**Comment by st235** [comment]
Hi @jedi2610,

can you record a video, please?

Best wishes,
Alexander Dadukin

**Comment by jedi2610** [comment]
![anroid](https://user-images.githubusercontent.com/30691152/92352491-d1784880-f0fb-11ea-9162-3df1df221f34.gif)

HomeFragment file: https://termbin.com/30og
Acitvity main file: https://termbin.com/1ijnr

**Comment by st235** [comment]
I will take a look asap

**Comment by jedi2610** [comment]
alr @st235

**Comment by st235** [comment]
@jedi2610 hi 👋

unfortunately, it's not an issue. Your layout is too complex: nested coordinator layout consumes all the events, so, that's why top-level coordinator layout cannot detect scroll and proceed it to the behaviour. 

I will investigate this further, but there is no solution at the time, except reduce the complexity of the layout. I am really sorry, that I dont have any better news for you.

Kind regards,
Alexander Dadukin

**Comment by jedi2610** [comment]
so what you're saying is that since i have 2 coordinator layouts (one in main activity and an other one in the home fragment),
the scroll events are not passed to the top-level coordinator layout(main activity) and instead they are being passed to the local coordinator layout (home fragment), right? so maybe if i remove the coordinator layout in my home fragment it would work?

**Comment by st235** [comment]
Yeah, if you remove your coordinator from home fragment it should work

**Comment by jedi2610** [comment]
![untitled](https://user-images.githubusercontent.com/30691152/92449613-f17d3a00-f1d7-11ea-8949-c0a7abd54681.gif)

now it works but it's just sooo broke :laughing:

**Comment by jedi2610** [comment]
i'm actually trying to pass scroll events to the parent coordinator layout but still it doesn't work. have any idea to implement this?
```
coordinatorLayout.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                if (motionEvent.getAction() == MotionEvent.ACTION_UP || motionEvent.getAction() == MotionEvent.ACTION_DOWN) {
                    Log.i(TAG, "onTouch: Passed");
                    getActivity().findViewById(R.id.coordinator_layout).onTouchEvent(motionEvent);
                    return true;
                }
                return false;
            }
        });
mRecyclerView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                if (motionEvent.getAction() == MotionEvent.ACTION_UP || motionEvent.getAction() == MotionEvent.ACTION_DOWN) {
                    Log.i(TAG, "onTouch: Passed");
                    getActivity().findViewById(R.id.coordinator_layout).onTouchEvent(motionEvent);
                    return true;
                }
                return false;
            }
        });
```

`mRecyclerView` and `coordinatorLayout` are custom class where i override only the `performClick` method. (it throws an error if i don't implement it)

**Comment by st235** [comment]
It’s not clear - why you need it?

**Comment by st235** [comment]
yeah, probably, it will not work)

**Comment by jedi2610** [comment]
@st235 yeah it's not working. i searched the internet an entire day but still no luck, couldn't find any answers. although it's clear that the local `CoordinatorLayout` is receiving all events, i don't know how to pass it on to the parent `CoordinatorLayout`.
do you  know how to pass those events?  can you please help me out on this one?

**Comment by st235** [comment]
The problem requires a lot of investigation here.
So, not all the events are consumed by the coordinator layout, but only that events, which can be classified as a nested scroll. When coordinator layout finds a scroll pattern it will consume the events. Unfortunately, in your example nested scroll consumed by the inner coordinator as long as you have `AppBarLayout` - if you remove `AppBarLayout` nested coordinator will work like a charm inside of outer one as it will not consume nested scroll events. 
So, currently, I don't know what the fix is the best one for your problem - I will investigate the problem further and maybe find some fixes from the library side, but my current answer stays still the same - you need to reduce the complexity of your layout 😄

**Comment by st235** [comment]
Maybe a better solution, for now, will be:
- Listen to the scroll inside of a fragment
- Hide bottom bar from fragment, for example

**Comment by jedi2610** [comment]
alr cool thanks. is there a method from the library side that i could invoke to hide the bottom bar?

**Comment by st235** [comment]
Yeah, as I said before - you are welcomed here, so, no need to apologize if you don't understand something.

Yeah, I don't have such methods (ie show/hide) in a view yet, but I have plans to release it soon.

**Comment by jedi2610** [comment]
that's great to hear. looking out for the new version then. thanks

**Comment by st235** [comment]
@jedi2610 hi 👋,

`1.2.4` is in live now. Currently, there were implemented `hide` and `show` methods.

**Comment by jedi2610** [comment]
hey alr thanks. i have a question tho. does the library try to instantiate the fragments anywhere?

**Comment by st235** [comment]
Cool, I am glad that you problem is resolved 😃
