### ISSUE TITLE
How add badge for menu items?

### ISSUE THREAD

**Issue by dino-sunny** [st235/ExpandableBottomBar#56]
How to add notification badge for menu items bottomNavigation.getOrCreateBadge(menuItemId)?

**Comment by st235** [comment]
Hi @dino-sunny, 

Unfortunately, there is no such an option right now, but it's a really good highlight. I planned to add this feature in upcoming releases, so now I am pretty sure it should be useful.

Kind regards,
Alexander Dadukin

**Comment by dino-sunny** [comment]
Great. Looking forward to it.

**Comment by st235** [comment]
@dino-sunny, hi 👋

huge PR with proposed changed is prepared. You can find it in linked pull requests. Probably, the changes will be live on a next week with a new major version `1.3.0`. Meanwhile, you can take a look at the new up.

I will post an update here when `1.3.0` will be released.

**Comment by st235** [comment]
@dino-sunny, hi again 👋

`1.3.0` is in live now 🎉

**Comment by dino-sunny** [comment]
Hi,

Sounds great.
