### ISSUE TITLE
custom font support for text in bottom bar

### ISSUE THREAD

**Issue by jedi2610** [st235/ExpandableBottomBar#57]
it would be nice to have custom font support for text in bottom nav bar

**Comment by st235** [comment]
Hi @jedi2610 👋

Dunno, I am not 100% confident in this. I need to check `BottomNavigationView` for this.

**Comment by jedi2610** [comment]
alr cool, i actually don't need that but thought it would be cool to have that feature

**Comment by st235** [comment]
Hi @jedi2610 👋

About custom fonts: it's already supported. To provide custom font you need:

1. Add custom font under `res/font` folder
2. Create a custom style with `fontFamily` property

```xml
    <style name="CustomFont">
        <item name="android:fontFamily">@font/ranches</item>
    </style>
```

3. Implement `android:theme` attribute at `ExpandableBottomBar`

```xml
    <github.com.st235.lib_expandablebottombar.ExpandableBottomBar
        android:id="@+id/expandable_bottom_bar"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:theme="@style/CustomFont"
        app:exb_items="@menu/bottom_bar"
        app:exb_itemInactiveColor="#CCCCCC"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />
```

The result should be like that:

![Screenshot_1600630321](https://user-images.githubusercontent.com/14966197/93720412-7d587400-fb91-11ea-9000-b05dd25ec19b.png)
![Screenshot_1600630324](https://user-images.githubusercontent.com/14966197/93720413-7e89a100-fb91-11ea-939e-3b3cffc49bca.png)

**Comment by jedi2610** [comment]
oh cool thanks
