### ISSUE TITLE
dynamic item control

### ISSUE THREAD

**Issue by hexlay** [st235/ExpandableBottomBar#66]
Hello,
It would be great if we could dinamically add/remove or hide item after bottom bar init...

P.S or list getter/setter to manipulate manually.

**Comment by st235** [comment]
Hi @hexlay 👋

Thank you for using this library! 

Can you, please, tell me a little bit more about your proposal? Which functionality do you need, like, changing text or images? Also, can you describe the situation when this would be useful?

Best wishes,
Alex

**Comment by hexlay** [comment]
> Hi @hexlay 👋
> 
> Thank you for using this library!
> 
> Can you, please, tell me a little bit more about your proposal? Which functionality do you need, like, changing text or images? Also, can you describe the situation when this would be useful?
> 
> Best wishes,
> Alex

Sorry for late reply....

For example: 
1. Ability to disable and enable items to prevent clicking while loading...
2. Ability to hide or unhide (add or remove) certain element to use single navigation resource for different (alike) purposes

However right now there's little control over items. Yes, we can add items, but removing or editing is not possible and i can only select item by its position, but not with item id.

Thanks in advanced !

**Comment by st235** [comment]
Hi @hexlay,

You can `show/hide` menuItem starting from `1.3.2`. You can find the migration guild [here](https://github.com/st235/ExpandableBottomBar/wiki/Migration).

>  i can only select item by its position, but not with item id.

It is not exactly true. As you can see in the definition of the [method](https://github.com/st235/ExpandableBottomBar/blob/master/lib-expandablebottombar/src/main/java/github/com/st235/lib_expandablebottombar/ExpandableBottomBar.kt#L284) it allows you   to select `item` by id.

Best wishes,
Alex
