### ISSUE TITLE
Default Item selection

### ISSUE THREAD

**Issue by prateekcode** [st235/ExpandableBottomBar#71]
Hey, thanks for this amazing library.
Can you please let me know how I can select the position by default instead of its always-on first position?

**Comment by st235** [comment]
Hello 👋 

Sorry for the delay. First of all, I would like to say thank you for using this library and raising important questions. 
Unfortunately, there is no method for default selection, but I believe that you can use the usual [select](https://github.com/st235/ExpandableBottomBar/blob/master/lib-expandablebottombar/src/main/java/github/com/st235/lib_expandablebottombar/Menu.kt#L39) during screen initialziation.

Please, let me know if this works for you

**Comment by prateekcode** [comment]
Hey,
Actually, I have some cards in my Dashboard and I want to navigate to another fragment upon click. I can switch to fragment but your bottom navigation exits on the same place that's why I want to ask u.

I will try to make this possible in your library.
