### ISSUE TITLE
There was a problem when importing version 1.4.0

### ISSUE THREAD

**Issue by liuxiaoliu66** [st235/ExpandableBottomBar#73]
When using version 1.4.0, studio cannot find
ExpandableBottomBar, when I changed to version 1.3.0, it can run normally. I have tried to clear the cache. I don't know if this is an example?

**Comment by st235** [comment]
Hello @liuxiaoliu66 👋 

First of all, thank you for using this library. I will check this problem ASAP and will post the result here.

Best wishes,
Alex

**Comment by st235** [comment]
Looks like maven central has the latest version available: https://search.maven.org/artifact/com.github.st235/expandablebottombar

What repositories do you use in your project? Maybe you forget to add **mavenCentral**, can you check it, please?

**Comment by liuxiaoliu66** [comment]
Thank you, this problem has been solved!
