### ISSUE TITLE
Failed to resolve:

### ISSUE THREAD

**Issue by shahzad1** [st235/ExpandableBottomBar#88]
Is this the latest release?
`Failed to resolve: com.github.st235:expandablebottombar:1.4.2`

**Comment by st235** [comment]
Hello @shahzad1 👋

Thank you very much for supporting the library.
The latest version is [1.5.1](https://search.maven.org/artifact/com.github.st235/expandablebottombar/1.5.1/aar).

P.S.: you should also use `mavenCentral` repo for your dependencies

Best,
Alex
